//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tarasova_DEntities : DbContext
    {
        public Tarasova_DEntities()
            : base("name=Tarasova_DEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<OfficeStaff> OfficeStaff { get; set; }
        public virtual DbSet<SystAdminStaff> SystAdminStaff { get; set; }
        public virtual DbSet<TypeProblem> TypeProblem { get; set; }
    }
}
