//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystAdminStaff
    {
        public int IDAdminEmployee { get; set; }
        public string AdminFullName { get; set; }
        public string AdminLogin { get; set; }
        public string AdminPassword { get; set; }
        public Nullable<int> IDdepartment { get; set; }
    
        public virtual Departments Departments { get; set; }
    }
}
